config/routes.rb
GinImport::Engine.routes.draw do
  root to: 'import_strategies#new'
  resources :import_strategies, only: [:index, :show, :new, :create]
  get  '/import'            , to: 'import_strategies#new'
  post '/preview_source'    , to: 'import_strategies#preview_source'    , as: :preview
  post '/test_cypher'       , to: 'import_strategies#test_cypher'       , as: :test
  post '/import'            , to: 'import_strategies#commit_import'     , as: :commit_import
  get  '/preview_collection', to: 'import_strategies#preview_collection', as: :preview_collection
end

app/models/gin_import/application_record.rb
module GinImport
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/gin_import/import_strategy.rb
module GinImport
  class ImportStrategy < ApplicationRecord
    self.table_name = GinImport.config.import_table_name

    URLCOLLECTIONTYPES = [:range, :csv, :api]

    validates_presence_of :model ,:url ,:document_type

    belongs_to :owner, class_name: GinImport.config.user_model_name.to_s.camelize if GinImport.config.user_model_name


    enum document_type: { json: 0 }
    enum url_type: { static: 0, dynamic: 1 }
  end
end

app/controllers/gin_import/application_controller.rb
module GinImport
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/gin_import/import_strategies_controller.rb
module GinImport
  class ImportStrategiesController < ApplicationController
    layout 'application'
    before_action :set_model_list

    def show

    end

    def index
      @import_strategies = GinImport.user_model_name ? ImportStrategy.where(owner_id: method(Ginimport.current_owner).id) : ImportStrategy.all
    end

    def new
      @import_strategy = ImportStrategy.new
    end

    def create
      @import_strategy = ImportStrategy.new(import_strategy_params)
      respond_to do |format|
        if @import_strategy.save
          format.html { redirect_back }
          format.js
        else
          format.html { render :show }
          format.js
        end
      end
    end

    def edit
      @import_strategy = ImportStrategy.find(params[:id])
    end

    def update
      @import_strategy = ImportStrategy.find(params[:id])
      respond_to do |format|
        if @import_strategy.save
          format.html { redirect_back }
          format.js
        else
          format.html { render :show }
          format.js
        end
      end
    end

    def preview_collection
      @url_collection = ApiCollectionService.new(url: params[:url], keys: params[:keys]).call!
      @import_strategy = ImportStrategy.new(session[:import_strategy])
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end

    def preview_source
      if params[:id].present?
        @import_strategy = ImportStrategy.find(params[:id])
        if params[:import_strategy].present?
          @import_strategy.assign_attributes(import_strategy_params)
        end
      else
        @import_strategy = ImportStrategy.new(import_strategy_params)
      end
      session[:import_strategy] = import_strategy_params
      generate_preview
    end

    def test_cypher
      @import_strategy = params[:id] ? ImportStrategy.find(params[:id]) : @import_strategy = ImportStrategy.new(session[:import_strategy])
      @preview = JSON.parse(params[:preview])
      @cypher = cypher_params
      session[:cypher] = cypher_params
      @import_strategy.cypher = @cypher
      @test = StrategyTestService.new(preview: @preview, cypher: @cypher.to_hash, import_strategy: @import_strategy).call!
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end

    def commit_import
      @import_strategy = params[:id] ? ImportStrategy.find(params[:id]) : @import_strategy = ImportStrategy.new(session[:import_strategy])
      @cypher = session[:cypher]
      @import_strategy.cypher = @cypher
      service = ImportService.new(import_strategy: @import_strategy)
      @result = service.call!
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end

    private

    def set_model_list
      @models = GinImport.get_model_list
    end

    def import_strategy_params
      params.require(:import_strategy).permit(:model, :multiple, :url, :url_type, :url_collection, :document_type)
    end

    def cypher_params
      params.require(:model).permit!
    end

    def generate_preview
      if @import_strategy.valid?
        @preview = PreviewService.new(import_strategy: @import_strategy).call!
      end
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end
end

app/helpers/gin_import/application_helper.rb
module GinImport
  module ApplicationHelper
  end
end

app/views/gin_import/forms/_cypher_form.html.erb
<h2>Cypher:</h2>
<%= simple_form_for :model, url: gin_import.test_path(id: import_strategy), remote: true do |f| %>
  <%= hidden_field_tag :import_id, import_strategy.id %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= text_area_tag 'preview', preview.to_json, hidden: true, style: 'width: 100%; height: 20vh;' %>
  <% if import_strategy.multiple? %>
    <div class="form-group string required model_collection">
      <%= label_tag :model_collection, 'collection start', class: "form-control-label string required" %>
      <%= text_field_tag 'model[collection]', nil, placeholder: 'sequence of keys as comma separated values', class: "form-control string optional" %>
    </div>
  <% end %>
  <% import_strategy.model.constantize.new.attributes.each do |key, value| %>
    <% unless ['id', "created_at", "updated_at"].include? key %>
      <%= f.input key, input_html: { value: value, name: "model[#{key}][shovel]" }, placeholder: 'sequence of keys as comma separated values' %>
      <div>
        <p><%= "#{key} transformation" %></p>
        <%= label_tag :replace %>
        <%= text_field_tag "model[#{key}][regex][replace]" %>
        <%= label_tag :with %>
        <%= text_field_tag "model[#{key}][regex][with]" %>
      </div>
    <% end %>
  <% end %>
  <%= f.submit 'test cypher' %>
<% end %>
<div id="test-result">
</div>

app/views/gin_import/forms/_import_strategy_form.html.erb
<%= simple_form_for import_strategy, url: gin_import.preview_path(id: import_strategy), remote: true do |f| %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= f.input :model, as: :select, collection: models %>
  <%= f.input :multiple, as: :radio_buttons %>
  <%= f.input :url %>
  <%= f.input :url_type, as: :radio_buttons, collection: GinImport::ImportStrategy.url_types.keys %>
  <div class="collection">
    <%= f.fields_for :dynamic_id do |ff| %>
      <%= ff.input :type, as: :radio_buttons, item_wrapper_class: 'form-check inline-radio',collection: GinImport::ImportStrategy::URLCOLLECTIONTYPES %>
      <div class='collection-range'>
        <%= ff.input :range_min %><%= ff.input :range_max %>
      </div>
      <div class='collection-csv'>
        <%= ff.input :csv %>
      </div>
      <div class='collection-api'>
        <%= ff.input :url %><%= ff.input :keys %>
      </div>
    <% end %>
    <%= link_to 'preview collection', preview_collection_path, remote: true, onclick: 'addParam(this)' %>
  </div>
  <textarea class="form-control json optional" name="import_strategy[url_collection]" id="import_strategy_url_collection"><%= @url_collection&.join(',') %></textarea>
  <%= f.input :document_type, as: :radio_buttons, collection: GinImport::ImportStrategy.document_types.keys %>
  <%= f.submit :preview %>
<% end %>

<script type="text/javascript">
  function addParam(link){
    link.href += "?url=" + document.getElementById('import_strategy_dynamic_id_url').value;
    link.href += "&keys=" + document.getElementById('import_strategy_dynamic_id_keys').value;
    return true;
  }
</script>

app/views/gin_import/import_strategies/_import_strategy.html.erb
<%# if @import_strategy %>
<div class="import_strategy-card" id='import_strategy-<%= import_strategy.id %>' >
  <% import_strategy.attributes.each do |key, value| %>
    <div class="import_strategy-attribute">
      <p><strong><%= key %></strong><%= value %></p>
    </div>
  <% end %>
  <div class="import_strategy-links">
    <%= link_to :preview_strategy, gin_import.preview_import_strategy_path(import_strategy) %>
    <%= link_to :test_strategy, gin_import.test_import_strategy_path(import_strategy) %>
  </div>
</div>
<%# end %>

app/views/gin_import/import_strategies/index.html.erb
<%= render @import_strategies %>

app/views/gin_import/import_strategies/new.html.erb
<%= stylesheet_link_tag "gin_import/application" %>


<%= render 'gin_import/forms/import_strategy_form', import_strategy: @import_strategy, models: @models %>
<div id="preview">
  <% if @preview %>
    <%= render("gin_import/previews/#{@import_strategy.document_type}", preview: @preview) %>
    <%= render "gin_import/forms/cypher_form", import_strategy: @import_strategy, preview: @preview %>
  <% end %>
</div>
<div id="test_result">
  <% if @test %>
    <%= render "gin_import/previews/model", import_strategy: @import_strategy, test_model: @test %>
  <% end %>
</div>
<div id="result">
  <% if @result %>
    <% if @result.class == 'Array' %>
      <% @result.each do |res| %>
        <%= render 'gin_import/partials/result', result: res %>
      <% end %>
    <% else %>
      <%= render 'gin_import/partials/result', result: @result %>
    <% end %>
  <% end %>
</div>

app/views/gin_import/import_strategies/preview_collection.js.erb
document.getElementById('import_strategy_url_collection').value = '<%= @url_collection.join(",") %>';

app/views/gin_import/import_strategies/preview_source.js.erb
document.getElementById('preview').innerHTML = '<%= j render "gin_import/previews/#{@import_strategy.document_type}", preview: @preview, import_strategy: @import_strategy %>';
document.getElementById('preview').innerHTML += '<%= j render "gin_import/forms/cypher_form", preview: @preview, import_strategy: @import_strategy %>';

app/views/gin_import/import_strategies/show.html.erb
<%= render @import_strategy %>

app/views/gin_import/import_strategies/test_cypher.js.erb
document.getElementById('test-result').innerHTML = '<%= j render "gin_import/previews/model", test_model: @test, import_strategy: @import_strategy %>'

app/views/gin_import/partials/_async_results.html.erb
_async_results.html.erb

app/views/gin_import/partials/_result.html.erb
<% if GinImport.config.actioncable_channel %>
  <%= render 'partials/async_results' %>
<% else %>
  <% if result.class == Array %>
    <% result.each do |r| %>
      <p><%= r.inspect.to_s[0..80] %></p>
    <% end %>
  <% else %>
    <p><%= result.inspect %></p>
  <% end %>

<% end %>

app/views/gin_import/previews/_json.html.erb
<pre><%= JSON.pretty_generate(preview) %></pre>

app/views/gin_import/previews/_model.html.erb
<% test_model.attributes.each do |key, value| %>
  <% next if ['id', 'created_at', 'updated_at'].include? key %>
  <h4><%= key %></h4>
  <p><%= value %></p>
<% end %>
<%= button_to 'import', gin_import.commit_import_path(import_strategy.id) if test_model.valid? %>